package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 19 16:30:05 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String testBuild(String a);
}

