package model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 19 16:28:53 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CpacityMgmtErrorsCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public CpacityMgmtErrorsCollImpl() {
    }
}

