package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 19 16:20:29 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcNgiZoneMasterViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DcNgiZoneMasterViewImpl() {
    }
}

