package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 19 16:20:29 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcNgiZoneMasterViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_DCNGIZONEMASTER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DcZoneId,
        DcId,
        DcZoneNumber,
        DcZonePurpose,
        DcZoneDescription,
        NoOfSwitches,
        NoOfFilers,
        Activeyn,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DCZONEID = AttributesEnum.DcZoneId.index();
    public static final int DCID = AttributesEnum.DcId.index();
    public static final int DCZONENUMBER = AttributesEnum.DcZoneNumber.index();
    public static final int DCZONEPURPOSE = AttributesEnum.DcZonePurpose.index();
    public static final int DCZONEDESCRIPTION = AttributesEnum.DcZoneDescription.index();
    public static final int NOOFSWITCHES = AttributesEnum.NoOfSwitches.index();
    public static final int NOOFFILERS = AttributesEnum.NoOfFilers.index();
    public static final int ACTIVEYN = AttributesEnum.Activeyn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DcNgiZoneMasterViewRowImpl() {
    }
}

